site_name: Norwegian Motion Laboratory

pages:
  - Home : index.md
  - About : about.md
  - Code : 
      - 'Code MD' : 'code.md'
      - 'Code RST' : 'code_rst.rst'
  - Graphics : img.md
  - Code_RST : code_rst.rst
theme: readthedocs